[tools]
node = '24'

[hooks]
# Enabling corepack will install the `pnpm` package manager specified in your package.json
# alternatively, you can also install `pnpm` with mise
postinstall = 'npx corepack enable'

[settings]
# This must be enabled to make the hooks work
experimental = true

[env]
_.path = ['./node_modules/.bin']

[tasks.pnpm-install]
description = 'Installs dependencies with pnpm'
run = 'pnpm install'
sources = ['package.json', 'pnpm-lock.yaml', 'mise.toml']
outputs = ['node_modules/.pnpm/lock.yaml']

[tasks.lint]
description = 'Calls your lint script in `package.json`'
run = 'node --run lint'
depends = ['pnpm-install']

[tasks.build]
description = 'Calls your build script in `package.json`'
run = 'node --run build'
depends = ['pnpm-install']
